version: '3.4'

services:
  seserver:
    image: seserver
    build:
      context: se-server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
